"use client";

import {
  CheckCircle2,
  Clock3,
  Copy,
  Globe2,
  MapPin,
  Navigation,
  ShieldCheck,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { toast } from "@/components/ui/toast";
import type { ILiveLocation } from "@/types/location.type";

interface LocationInfoDialogProps {
  location: ILiveLocation | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

const LocationInfoDialog = ({
  location,
  open,
  onOpenChange,
}: LocationInfoDialogProps) => {
  if (!location) {
    return null;
  }

  const latitude = Number(location.latitude);
  const longitude = Number(location.longitude);

  const copyCoordinates = async () => {
    await navigator.clipboard.writeText(
      `${location.latitude}, ${location.longitude}`,
    );
    toast.add({
      title: "Coordinates copied!",
      description: "Coordinates copied successfully.",
      type: "success",
    });
  };

  const updatedAt = new Date(location.updatedAt).toLocaleString();

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-lg overflow-hidden rounded-3xl border-border/60 p-0">
        <div className="relative overflow-hidden">
          <div className="absolute -right-20 -top-20 size-52 rounded-full bg-primary/10 blur-3xl" />
          <div className="absolute -bottom-20 -left-20 size-52 rounded-full bg-blue-500/10 blur-3xl" />

          <div className="relative border-b border-border/60 bg-muted/20 px-6 py-6">
            <div className="flex items-start gap-4">
              <div className="flex size-12 shrink-0 items-center justify-center rounded-2xl bg-blue-500/10 text-blue-500">
                <Navigation className="size-6" />
              </div>

              <div className="min-w-0">
                <DialogHeader className="text-left">
                  <DialogTitle className="text-xl">
                    Current Location
                  </DialogTitle>

                  <DialogDescription className="mt-1">
                    Your latest location generated by SwiftCourier.
                  </DialogDescription>
                </DialogHeader>
              </div>
            </div>
          </div>

          <div className="relative space-y-4 p-6">
            <div className="rounded-2xl border border-border/60 bg-muted/30 p-4">
              <div className="mb-3 flex items-center gap-2">
                <MapPin className="size-4 text-primary" />

                <span className="text-sm font-semibold">Address</span>
              </div>

              <p className="text-sm leading-6 text-muted-foreground">
                {location.address?.fullAddress ||
                  "Address information unavailable"}
              </p>
            </div>

            <div className="grid gap-3 sm:grid-cols-2">
              <div className="rounded-2xl border border-border/60 bg-muted/20 p-4">
                <div className="mb-2 flex items-center gap-2 text-muted-foreground">
                  <Globe2 className="size-4" />
                  <span className="text-xs">Latitude</span>
                </div>

                <p className="font-mono text-sm font-semibold">
                  {latitude.toFixed(7)}
                </p>
              </div>

              <div className="rounded-2xl border border-border/60 bg-muted/20 p-4">
                <div className="mb-2 flex items-center gap-2 text-muted-foreground">
                  <Globe2 className="size-4" />
                  <span className="text-xs">Longitude</span>
                </div>

                <p className="font-mono text-sm font-semibold">
                  {longitude.toFixed(7)}
                </p>
              </div>
            </div>

            <div className="grid gap-3 sm:grid-cols-2">
              <div className="flex items-center gap-3 rounded-2xl border border-border/60 bg-muted/20 p-4">
                <div className="flex size-9 items-center justify-center rounded-xl bg-emerald-500/10 text-emerald-500">
                  <CheckCircle2 className="size-4" />
                </div>

                <div>
                  <p className="text-xs text-muted-foreground">Status</p>

                  <p className="text-sm font-semibold">{location.status}</p>
                </div>
              </div>

              <div className="flex items-center gap-3 rounded-2xl border border-border/60 bg-muted/20 p-4">
                <div className="flex size-9 items-center justify-center rounded-xl bg-violet-500/10 text-violet-500">
                  <Clock3 className="size-4" />
                </div>

                <div className="min-w-0">
                  <p className="text-xs text-muted-foreground">Updated</p>

                  <p className="truncate text-sm font-semibold">{updatedAt}</p>
                </div>
              </div>
            </div>

            <div className="flex items-center gap-3 rounded-2xl border border-primary/15 bg-primary/5 p-4">
              <ShieldCheck className="size-5 shrink-0 text-primary" />

              <p className="text-xs leading-5 text-muted-foreground">
                Location data is generated from your device's current
                coordinates.
              </p>
            </div>

            <Button
              type="button"
              variant="outline"
              className="w-full rounded-xl"
              onClick={copyCoordinates}
            >
              <Copy className="size-4" />
              Copy Coordinates
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default LocationInfoDialog;
